---
root: true

env:
  browser: true
  es6: true
  node: true

globals:
  Atomics: readonly
  SharedArrayBuffer: readonly

parserOptions:
  project: ./tsconfig.json
extends:
  - airbnb
  - airbnb/hooks
  - airbnb-typescript
rules:
  '@typescript-eslint/semi': 'off'
